"use client";
import { FormEvent, useEffect, useState } from "react";
type RequestItem={id:string;requestId:string;serviceType:string;customer:{name:string;email:string}};
export default function QuotationsAdmin(){
 const[data,setData]=useState<RequestItem[]>([]),[requestId,setRequestId]=useState(""),[scope,setScope]=useState(""),[price,setPrice]=useState("0"),[discount,setDiscount]=useState("0"),[extras,setExtras]=useState("0"),[terms,setTerms]=useState(""),[revisionCount,setRevisionCount]=useState("2"),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/admin/requests").then(async r=>{const x=await r.json();if(r.ok)setData(x.requests||[])}).catch(()=>{})},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");const r=await fetch("/api/admin/quotations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestId,scope,price:Number(price),discount:Number(discount),extras:Number(extras),terms,revisionCount:Number(revisionCount)})});const x=await r.json();if(!r.ok){setError(x.error||"Quotation gagal dibuat");return}setMessage("Quotation "+x.quotation.id+" berhasil dibuat.");setScope("");setTerms("");setPrice("0");setDiscount("0");setExtras("0")}
 return <main className="page"><div className="eyebrow">ADMIN / QUOTATIONS</div><h1>Quotation Management</h1><form onSubmit={submit} className="card p-6 max-w-4xl mt-8 stack"><select required value={requestId} onChange={e=>setRequestId(e.target.value)}><option value="">Pilih request</option>{data.map(r=><option value={r.requestId} key={r.id}>{r.requestId} · {r.customer.name} · {r.serviceType}</option>)}</select><textarea required maxLength={10000} rows={6} placeholder="Scope pekerjaan" value={scope} onChange={e=>setScope(e.target.value)}/><div className="grid md:grid-cols-4 gap-3"><input required type="number" min="0" placeholder="Price" value={price} onChange={e=>setPrice(e.target.value)}/><input type="number" min="0" placeholder="Discount" value={discount} onChange={e=>setDiscount(e.target.value)}/><input type="number" min="0" placeholder="Extras" value={extras} onChange={e=>setExtras(e.target.value)}/><input type="number" min="0" placeholder="Revisions" value={revisionCount} onChange={e=>setRevisionCount(e.target.value)}/></div><textarea required maxLength={10000} rows={5} placeholder="Terms" value={terms} onChange={e=>setTerms(e.target.value)}/><button className="btn btn-primary" type="submit">Create Quotation</button>{message&&<p role="status" className="text-emerald-700">{message}</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}</form><section className="card p-6 mt-8"><h2>Request Queue</h2><div className="stack mt-4">{data.map(r=><div className="flex flex-wrap justify-between gap-3 border-b border-violet-100 dark:border-neutral-800 py-3" key={r.id}><span><b>{r.requestId}</b> · {r.serviceType}</span><span className="muted">{r.customer.email}</span></div>)}</div></section></main>
}
