"use client";
import { FormEvent, useEffect, useState } from "react";

type Product={id:string;productId:string;name:string;category:string;price:number;discount:number;version:string;status:string;salesCount:number};

export default function ProductsAdmin(){
  const[data,setData]=useState<Product[]>([]),[name,setName]=useState(""),[category,setCategory]=useState("3D"),[price,setPrice]=useState("0"),[description,setDescription]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
  async function load(){setLoading(true);try{const r=await fetch("/api/admin/products");const x=await r.json();if(!r.ok)throw new Error(x.error||"Gagal memuat produk");setData(x.products||[])}catch(e){setError(e instanceof Error?e.message:"Gagal memuat produk")}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function create(e:FormEvent){e.preventDefault();setError("");setMessage("");const r=await fetch("/api/admin/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,category,price:Number(price),description,status:"DRAFT"})});const x=await r.json();if(!r.ok){setError(x.error||"Produk gagal dibuat");return}setMessage("Produk berhasil dibuat.");setName("");setPrice("0");setDescription("");load()}
  async function archive(id:string){const r=await fetch("/api/admin/products/"+encodeURIComponent(id),{method:"DELETE"});if(r.ok)load();else{const x=await r.json();setError(x.error||"Archive gagal")}}
  return <main className="page"><div className="eyebrow">ADMIN / PRODUCTS</div><h1>Product Management</h1><form onSubmit={create} className="card p-6 max-w-4xl mt-8 stack"><input required maxLength={160} placeholder="Nama produk" value={name} onChange={e=>setName(e.target.value)}/><div className="grid md:grid-cols-2 gap-4"><input required maxLength={80} placeholder="Kategori" value={category} onChange={e=>setCategory(e.target.value)}/><input required type="number" min="0" step="1" placeholder="Harga" value={price} onChange={e=>setPrice(e.target.value)}/></div><textarea required maxLength={10000} rows={5} placeholder="Deskripsi" value={description} onChange={e=>setDescription(e.target.value)}/><button className="btn btn-primary" type="submit">Create Product</button>{message&&<p role="status" className="text-emerald-700">{message}</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}</form><section className="stack mt-8">{loading?<p className="muted">Memuat...</p>:data.map(p=><article className="card p-5" key={p.id}><div className="flex flex-wrap justify-between gap-4"><div><b>{p.name}</b><p className="text-sm muted mt-1">{p.productId} · {p.category} · v{p.version}</p></div><span className="text-xs text-violet-700">{p.status}</span></div><div className="flex flex-wrap justify-between gap-4 mt-4 text-sm"><span>{p.price.toLocaleString("id-ID")} IDR · diskon {p.discount}% · sales {p.salesCount}</span><button className="btn" type="button" onClick={()=>archive(p.id)} disabled={p.status==="ARCHIVED"}>Archive</button></div></article>)}</section></main>
}
