"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { formatIDR } from "@/lib/data";

type Quote={id:string;total:number;revisionCount:number;validUntil:string;approvedAt:string|null};
type RequestItem={requestId:string;serviceType:string;requestedProduct:string|null;description:string;deadline:string|null;budget:number|null;status:string;quotedPrice:number|null;revisionLimit:number;updatedAt:string;quotations:Quote[]};
const steps=["SUBMITTED","REVIEWING","QUOTATION","WAITING_PAYMENT","PAID","IN_PROGRESS","REVISION","FINAL_REVIEW","COMPLETED"];

export default function Requests(){
  const[data,setData]=useState<RequestItem[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  useEffect(()=>{fetch("/api/requests").then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||"Gagal memuat request");setData(x.requests||[])}).catch(e=>setError(e instanceof Error?e.message:"Gagal memuat request")).finally(()=>setLoading(false))},[]);
  return <main className="page"><div className="eyebrow">CUSTOM REQUEST</div><div className="flex flex-wrap justify-between gap-4 items-end"><div><h1>My Requests</h1><p className="muted mt-2">Pantau brief, quotation, pembayaran, produksi, dan revisi.</p></div><Link className="btn btn-primary" href="/request">Buat Request</Link></div>{loading&&<p className="muted mt-8">Memuat request...</p>}{error&&<div className="card p-5 mt-8 text-red-700" role="alert">{error}</div>}{!loading&&!error&&!data.length&&<section className="card p-6 mt-8">Belum ada request. <Link className="text-violet-700 underline" href="/request">Buat request baru.</Link></section>}<div className="stack mt-6">{data.map(item=>{const active=Math.max(0,steps.indexOf(item.status));return <article className="card p-6" key={item.requestId}><div className="flex flex-wrap justify-between gap-4"><div><b>{item.requestId}</b><h2 className="text-xl font-bold mt-1">{item.serviceType}</h2>{item.requestedProduct&&<p className="muted mt-1">{item.requestedProduct}</p>}</div><span className="text-xs text-violet-700">{item.status}</span></div><p className="mt-4 text-neutral-700 dark:text-neutral-200 whitespace-pre-line">{item.description}</p><div className="grid md:grid-cols-3 gap-3 mt-5 text-sm"><div><span className="muted">Deadline</span><b className="block mt-1">{item.deadline?new Date(item.deadline).toLocaleDateString("id-ID"):"Belum ditentukan"}</b></div><div><span className="muted">Budget</span><b className="block mt-1">{item.budget!==null?formatIDR(item.budget):"Custom Quote"}</b></div><div><span className="muted">Quoted Price</span><b className="block mt-1">{item.quotedPrice!==null?formatIDR(item.quotedPrice):"Menunggu review"}</b></div></div><div className="mt-6 overflow-x-auto"><div className="min-w-[720px] grid grid-cols-9 gap-2">{steps.map((step,index)=><div key={step} className={"rounded-xl border p-3 text-center text-xs "+(index<=active?"border-violet-400 bg-violet-50 text-violet-900":"border-violet-100 text-neutral-400")}><span className="font-bold">{index+1}</span><div className="mt-1">{step.replaceAll("_"," ")}</div></div>)}</div></div>{item.quotations.length>0&&<div className="mt-6 stack">{item.quotations.slice(0,3).map(q=><div className="rounded-2xl border border-violet-100 dark:border-neutral-800 p-4" key={q.id}><div className="flex flex-wrap justify-between gap-3"><b>Quotation</b><span className="text-sm">{q.approvedAt?"APPROVED":new Date(q.validUntil)<=new Date()?"EXPIRED":"WAITING APPROVAL"}</span></div><p className="text-sm muted mt-2">{formatIDR(q.total)} · {q.revisionCount} revisi · berlaku sampai {new Date(q.validUntil).toLocaleDateString("id-ID")}</p></div>)}</div>}</article>})}</div></main>;
}
