"use client";
import { FormEvent, useEffect, useState } from "react";
type Bundle={id:string;bundleId:string;name:string;description:string;discountPercent:number;active:boolean;items:{product:{productId:string;name:string}}[]};
export default function BundlesAdmin(){
 const[data,setData]=useState<Bundle[]>([]),[name,setName]=useState(""),[description,setDescription]=useState(""),[discount,setDiscount]=useState("10"),[products,setProducts]=useState("NS-PROD-000001,NS-PROD-000002"),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/bundles");const x=await r.json();if(!r.ok)throw new Error(x.error||"Gagal memuat bundle");setData(x.bundles||[])}catch(e){setError(e instanceof Error?e.message:"Gagal memuat bundle")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();setError("");setMessage("");const r=await fetch("/api/admin/bundles",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,description,discountPercent:Number(discount),products:products.split(",").map(x=>x.trim()).filter(Boolean)})});const x=await r.json();if(!r.ok){setError(x.error||"Bundle gagal dibuat");return}setMessage("Bundle dibuat.");setName("");setDescription("");load()}
 async function toggle(b:Bundle){const r=await fetch("/api/admin/bundles",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:b.id,active:!b.active})});const x=await r.json();if(r.ok)setData(prev=>prev.map(item=>item.id===b.id?{...item,active:x.bundle.active}:item));else setError(x.error||"Update bundle gagal")}
 return <main className="page"><div className="eyebrow">ADMIN / BUNDLES</div><h1>Bundle Management</h1><form onSubmit={create} className="card p-6 max-w-4xl mt-8 stack"><input required maxLength={160} placeholder="Nama bundle" value={name} onChange={e=>setName(e.target.value)}/><textarea required maxLength={5000} rows={4} placeholder="Deskripsi" value={description} onChange={e=>setDescription(e.target.value)}/><div className="grid md:grid-cols-2 gap-3"><input type="number" min="0" max="100" value={discount} onChange={e=>setDiscount(e.target.value)} placeholder="Diskon %"/><input required value={products} onChange={e=>setProducts(e.target.value)} placeholder="Product ID dipisah koma"/></div><button className="btn btn-primary" type="submit">Create Bundle</button>{message&&<p role="status" className="text-emerald-700">{message}</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}</form><div className="stack mt-8">{loading?<p className="muted">Memuat...</p>:data.map(b=><article className="card p-5" key={b.id}><div className="flex flex-wrap justify-between gap-4"><div><b>{b.name}</b><p className="text-sm muted mt-1">{b.bundleId} · {b.discountPercent}% · {b.active?"ACTIVE":"INACTIVE"}</p></div><button className="btn" type="button" onClick={()=>toggle(b)}>{b.active?"Nonaktifkan":"Aktifkan"}</button></div><p className="text-sm muted mt-3">{b.items.map(i=>i.product.name).join(" · ")}</p></article>)}</div></main>
}
